<?php
/**
 * Scheduler Admin Module
 *
 * @author      Neal Greimel <neal@greimel.us>
 * @copyright   Copyright (c) 2014 Neal Greimel (http://neal.greimel.us)
 */

$title = 'All appointments';
$this->headTitle($title);

?>


<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8">

      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-clock-o fa-fw"></i> Calendar
          <div class="pull-right">
            <div class="btn-group">
              <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                Actions <span class="caret"></span>
              </button>
              <ul class="dropdown-menu pull-right" role="menu">
                <li>
                  <a href="<?php echo $this->url('scheduler', array('action' => 'create')); ?>">Add new appointment</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-4">
              <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Date</th>
                      <th>Time</th>
                      <th>Event Id</th>
                      <th>&nbsp;</th>
                    </tr>
                  </thead>

                  <tbody>
                  <?php foreach ($events as $event): ?>
                    <tr>
                      <td><?php echo $event->id; ?></td>
                      <td><?php echo $event->date->format('Y-m-d'); ?></td>
                      <td><?php echo $event->time ? $event->time->format('g:i:s a') : ''; ?></td>
                      <td><?php echo $event->appointment->rei; ?></td>
                      <td>
                        <a href="<?php echo $this->url('scheduler', array('action' => 'edit', 'id' => $event->id)); ?>">Edit</a>
                        <a href="<?php echo $this->url('scheduler', array('action' => 'delete', 'id' => $event->id)); ?>">Delete</a>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="col-lg-8">
              <div id="morris-bar-chart"></div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>
