<?php echo $this->doctype(); ?>

<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->headTitle($this->translate('Scheduler'))->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()
                    ->prependStylesheet($this->cacheBust($this->basePath('css/style.css')))
                    ->prependStylesheet($this->cacheBust($this->basePath('css/bootstrap.min.css')))
    ; ?>

    <!-- Scripts -->
    <script src="<?php echo $this->cacheBust($this->basePath('js/vendor/modernizr-2.8.3.min.js')); ?>"></script>

    <?php echo $this->headScript()
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand active" href="<?php echo $this->url('home'); ?>"><span class="fa fa-calendar"></span>&nbsp;Home</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?php //echo $this->url('admin'); ?>"><span class="glyphicon glyphicon-th-list"></span>&nbsp;&nbsp;Calendar</a></li>
                <li><a href="#contactModal" data-toggle="modal"><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;Contact</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->content; ?>

      <hr />

      <footer>
        <p>Copyright &copy; <?php echo date('Y') ?> by Neal Greimel <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>
    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->cacheBust($this->basePath('js/vendor/jquery-1.11.1.min.js')); ?>"><\/script>')</script>
    <script src="<?php echo $this->cacheBust($this->basePath('js/bootstrap.min.js')); ?>"></script>
    <script src="<?php echo $this->cacheBust($this->basePath('js/vendor/jquery.cookie-1.4.1.min.js')); ?>"></script>
    <script src="<?php echo $this->cacheBust($this->basePath('js/contact.js')); ?>"></script>
    <!--[if lt IE 8]>
    <script src="<?php echo $this->cacheBust($this->basePath('js/browse.happy.js')); ?>"></script>
    <![endif]-->

    <?php echo $this->inlineScript(); ?>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-32811855-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>
