<?php
/**
 * Scheduler Module
 *
 * @author      Neal Greimel <neal@greimel.us>
 * @copyright   Copyright (c) 2014 Neal Greimel (http://neal.greimel.us)
 */

$title = 'Create new appointment';
$this->headTitle($title);

$form->setAttribute('action', $this->url('scheduler', array('action' => 'create')));
$form->prepare();

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div role="tabpanel">
<?php echo $this->form()->openTag($form); ?>

  <div class="tab-content">
    <?php $event = $form->get('event'); ?>
    <div role="tabpanel" class="tab-pane active" id="event">
      <div class="row">
        <div class="col-md-6">
          <div class="row">
            <div class="form-group col-xs-6">
              <?php echo $this->formHidden($event->get('id')); ?>
              <?php echo $this->formRow($event->get('date')); ?>
            </div>
            <div class="form-group col-xs-6 hidden">
              <?php echo $this->formRow($event->get('time')); ?>
            </div>
          </div>
          <div class="form-group">
            <a class="btn btn-primary tab" href="#appointment" aria-controls="appointment">Continue</a>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Help?</h3>
          <div class="row">
            <div class="col-xs-6">
              <ul>
                <li>Select a date from the calendar.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <?php $appointment = $event->get('appointment'); ?>
    <div role="tabpanel" class="tab-pane" id="appointment">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <?php echo $this->formHidden($appointment->get('id')); ?>
            <?php echo $this->formRow($appointment->get('rei')); ?>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($appointment->get('work_description')); ?>
          </div>
          <div class="form-group">
            <a class="btn btn-primary tab" href="#location" aria-controls="location">Continue</a>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Help?</h3>
          <div class="row">
            <div class="col-xs-6">
              <ul>
                <li>Your REI # is listed on your permit.</li>
                <li>
                  Be as descriptive as possible when detailing what needs
                  to be inspected.
                  <blockquote>
                    New basement bathroom, rough-in
                  </blockquote>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <?php $location = $appointment->get('location'); ?>
    <div role="tabpanel" class="tab-pane" id="location">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <?php echo $this->formHidden($location->get('id')); ?>
            <?php echo $this->formRow($location->get('street')); ?>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($location->get('city')); ?>
          </div>
          <div class="row">
            <div class="form-group col-xs-6">
              <?php echo $this->formRow($location->get('state')); ?>
            </div>
            <div class="form-group col-xs-6">
              <?php echo $this->formRow($location->get('zip')); ?>
            </div>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($location->get('access_type')); ?>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($location->get('access_info')); ?>
          </div>
          <div class="form-group">
            <input type="hidden" id="latitude" name="latitude" />
            <input type="hidden" id="longitude" name="longitude" />
            <input type="hidden" id="formatted_address" name="formatted_address" />

            <a class="btn btn-primary tab" href="#user" aria-controls="user">Continue</a>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Help?</h3>
          <div id="address-map" style="height:300px; width:100%; margin:0; padding:0;"></div>
        </div>
      </div>
    </div>

    <?php $user = $appointment->get('user'); ?>
    <div role="tabpanel" class="tab-pane" id="user">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <?php echo $this->formHidden($user->get('id')); ?>
            <?php echo $this->formRow($user->get('email')); ?>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($user->get('first_name')); ?>
            <?php echo $this->formRow($user->get('last_name')); ?>
          </div>
          <div class="form-group">
            <?php echo $this->formRow($user->get('phone')); ?>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Continue</button>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Help?</h3>
        </div>
      </div>
    </div>

  </div>

<?php echo $this->form()->closeTag(); ?>
</div>

<?php $this->headLink()->prependStylesheet($this->cacheBust($this->basePath('css/datepicker3.css'))); ?>
<?php $this->inlineScript()->prependFile($this->cacheBust($this->basePath('js/vendor/datepicker/bootstrap-datepicker.js'))); ?>
<?php $this->inlineScript()->prependFile('https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyA4uB7zJ10o3KaTB7NQ0Cbj1wZNv2BOnZI'); ?>
<?php $this->inlineScript()->captureStart(); ?>
(function ($) {
  //$('label[for="date"], #date').hide();
  $('#date').datepicker({
    autoclose: true,
    format: 'yyyy-mm-dd',
    startDate: '-1d',
    endDate: '+14d',
    todayBtn: 'linked',
    daysOfWeekDisabled: '0,6',
    todayHighlight: true,
    beforeShowDay: function (date) {
    }
  });

  $('a.tab, button[type="submit"]').click(function (e) {
    var $this      = $(this),
        $form      = $('#create-event'),
        fieldsetId = $this.closest('div[role="tabpanel"]').attr('id');
    $.ajax({
      dataType: 'json',
      url: $form.attr('action') + '?id=' + fieldsetId,
      data: $form.serialize()
    })
      .done(function (data) {
        if (data && data.success) {
          // Submit form
          if ('submit' == $this.attr('type')) {
            return true;
          } else {
            e.preventDefault();
            return $this.tab('show');
          }
        } else if (data && data.errors) {
          $('.has-error', $('#' + fieldsetId)).removeClass('has-error');
          $('.help-block', $('#' + fieldsetId)).remove();
          errors = data.errors;
          $('input,select,textarea', '#' + fieldsetId).each(function () {
            var name = $(this).attr('name').replace(/\[/g, '.').replace(/\]/g, '');
            var nameA = name.split('.');
            for (var i in nameA) {
              errors = errors[nameA[i]];
            }
            var msg = new Array;
            for (var i in errors) {
              msg.push(errors[i]);
            }
            if (msg.length) {
              $(this).closest('.form-group').addClass('has-error');
              $(this).after('<div class="help-block">' + msg.join('<br />') + '</div>');
            }

            errors = data.errors;
          });
        }

        console.log(e);
        e.preventDefault();
        console.log(e.isDefaultPrevented());
        alert('error in form');
        return false;

      })
      .fail(function (xhr, status, message) {
        console.log({ xhr: xhr, status: status, message: message });
        alert(status.toUpperCase() + ': ' + message);

        e.preventDefault();
        return false;
      });
  });

  $('#street, #city, #state, #zip').on('blur', function () {
    window.codeAddress();
  });
})(jQuery);

var geocoder;
var map;
var marker;
var geocoding = false;
var initialize = function() {
      geocoder = new google.maps.Geocoder();
      var latlng = new google.maps.LatLng(44.89, -93.28);
      var mapOptions = {
        zoom: 8,
        center: latlng
      };
      map = new google.maps.Map(document.getElementById('address-map'), mapOptions);
    };
var codeAddress = function() {
  if (geocoding) {
    return false;
  }
  geocoding = true;
  var address = new Array(
    document.getElementById('street').value,
    document.getElementById('city').value,
    document.getElementById('state').value,
    document.getElementById('zip').value,
    'USA'
  );
  geocoder.geocode({ 'address': address.join(', ') }, function (results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      document.getElementById('latitude').value = results[0].geometry.location.lat();
      document.getElementById('longitude').value = results[0].geometry.location.lng();
      document.getElementById('formatted_address').value = results[0].formatted_address;

      map.setCenter(results[0].geometry.location);
      map.setZoom(17);
      marker = new google.maps.Marker({
        map: map,
        draggable: true,
        animation: google.maps.Animation.DROP,
        position: results[0].geometry.location
      });

      google.maps.event.addListener(marker, 'dragend', dragMarker);

      console.log(results[0]);
    } else {
      console.log(status);
    }
    geocoding = false;
  });
};

var dragMarker = function () {
  if (marker.getPosition()) {
    console.log('Moved marker:', marker.getPosition());
    geocoder.geocode({ 'location': marker.getPosition() }, function (results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        document.getElementById('latitude').value = results[0].geometry.location.lat();
        document.getElementById('longitude').value = results[0].geometry.location.lng();
        document.getElementById('formatted_address').value = results[0].formatted_address;
      }
    });
  }
};

google.maps.event.addDomListener(window, 'load', initialize);

<?php $this->inlineScript()->captureEnd(); ?>
