<?php
/**
 * Scheduler Module
 *
 * @author      Neal Greimel <neal@greimel.us>
 * @copyright   Copyright (c) 2014 Neal Greimel (http://neal.greimel.us)
 */

$title = 'All appointments';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
  <a href="<?php echo $this->url('scheduler', array('action' => 'add')); ?>">Add new appointment</a>
</p>

<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>Time</th>
      <th>Event Id</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
  <?php foreach ($appointments as $appointment): ?>
    <tr>
      <td><?php echo $appointment->id; ?></td>
      <td><?php echo $appointment->date->format('Y-m-d'); ?></td>
      <td><?php echo $appointment->time->format('g:i:s a'); ?></td>
      <td><?php echo $appointment->event_id; ?></td>
      <td>
        <a href="<?php echo $this->url('scheduler', array('action' => 'edit', 'id' => $appointment->id)); ?>">Edit</a>
        <a href="<?php echo $this->url('scheduler', array('action' => 'delete', 'id' => $appointment->id)); ?>">Delete</a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
