<?php
/**
 * Scheduler Module
 *
 * @author      Neal Greimel <neal@greimel.us>
 * @copyright   Copyright (c) 2014 Neal Greimel (http://neal.greimel.us)
 */

$title = 'All appointments';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
  <a href="<?php echo $this->url('scheduler', array('action' => 'create')); ?>">Add new appointment</a>
</p>

<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>Time</th>
      <th>Event Id</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
  <?php foreach ($events as $event): ?>
    <tr>
      <td><?php echo $event->id; ?></td>
      <td><?php echo $event->date->format('Y-m-d'); ?></td>
      <td><?php echo $event->time ? $event->time->format('g:i:s a') : ''; ?></td>
      <td><?php echo $event->appointment->rei; ?></td>
      <td>
        <a href="<?php echo $this->url('scheduler', array('action' => 'edit', 'id' => $event->id)); ?>">Edit</a>
        <a href="<?php echo $this->url('scheduler', array('action' => 'delete', 'id' => $event->id)); ?>">Delete</a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
